spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:shorteningUrlDb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true

shortening-url:
  limit-key: 218340105584895
  max-length: 8
  digits-values: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  prefix-urls:
    - http://localhost:8080/

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:placeTestDb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true